[package]
name = "sui_index"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "edfb00f26f1e" }

[addresses]
sui_index = "0x0"
